GET http://localhost:8001/member/hello
Accept: application/json

###

GET http://localhost:8000/member/hello
Accept: application/json

###

GET http://47.101.44.52/member/hello
Accept: application/json

###
